### ISSUE TITLE
Raises an error on an empty document

### ISSUE THREAD

**Issue by no-reply** [ruby-rdf/rdf-turtle#14]
`RDF::Turtle::Reader.new('', validate: true).statements` fails with `RDF::ReaderError: Errors found during processing`.

I believe a zero character string is a valid turtle document, and that this should parse to an empty set of statements. Is this correct?

**Comment by no-reply** [comment]
I'm having trouble repeating this in an isolated environment. It's probable that this is a dependency issue.

**Comment by no-reply** [comment]
Can't repeat in a base `rdf` or `linkeddata` environment. I'll reopen if I can figure out what dependency combination caused this behavior for me.

**Comment by gkellogg** [comment]
You should see more detailed messages on street, or whatever the log device is. No reason I can think of that an empty graph would be a problem.
